### ISSUE TITLE
add option for set a custom name of chromium-flags.conf file

### ISSUE THREAD

**Issue by sl1pkn07** [foutrelis/chromium-launcher#1]
is possible add option to set a custom name of chromium-flags.conf?

option like a CHROMIUM_BIN or PREFIX variables in the makefile

gretings

**Comment by foutrelis** [comment]
I see your point, but I'm not sure if it'd be very useful. I mean, user flags can be shared by different Chromium versions as they are fairly static.

Do you have a specific use case in mind where this would be desired?

**Comment by sl1pkn07** [comment]
For example, i use different flags for each chromiun (one for stable and others for dev channel) the point is cover this type of config. I can make a 'sed in chromium-launcher.in, but is better and easy change the name in the makefile

Greetings

**Comment by sl1pkn07** [comment]
or changing full name, or add $(CHROMIUM_SUFFIX) in the name, like 'chromium$(CHROMIUM_SUFFIX)-flags.conf'

**Comment by foutrelis** [comment]
Yeah, that would work great as well. I'll try to add it soon.

**Comment by foutrelis** [comment]
~~Please give the `develop` branch a try. (You can do this by appending `#branch=develop` to the source URL in the PKGBUILD.) If you don't notice any issues, I'll merge it into `master` and tag a release so we don't use a moving branch as the source in our packages.~~

Please test the v1 release. Once you've updated chromium-dev to use the tagged release, I'll merge the develop branch into master. (Some [PKGBUILD changes](https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/chromium&id=d7e993560fc88965b093b5b7c601e9005344ed6f) are needed.)

Additionally, after the changes in commit 48d77d1667ed83e93f29a35d38ec02f4e0826f73 you don't need to specify CHROMIUM_BIN during `make install` anymore and you can drop the two sed calls from prepare() in your chromium-dev package.

Finally, after commit 5f40161240a995ca0067d90d49648e899397b305 we also don't need to call strip on launcher-errmsg in the PKGBUILD; instead there's an `install-strip` target that we can use instead of `install`.

**Comment by sl1pkn07** [comment]
Roger
